---
output: html_document
---

```{r setup, include=FALSE}
# root directory one down if using `prodigenr`
knitr::opts_chunk$set(echo = FALSE, eval = FALSE)
devtools::load_all()
library(tidyverse)
library(NetCoupler)
# library(ggraph)
# library(tidygraph)
conflicted::conflict_prefer("filter", "dplyr")
```

```{r load-data}
# load_data_as_job()
project_data <- load_data() %>% 
    rename(hba1c = mtb_glycated_haemoglobin_hba1c) %>% 
    select(
        # More than 25% missing for these variables.
        -mtb_microalbumin_in_urine,
        -mtb_lipoprotein_a,
        # Glucose should probably not be in models with HbA1c as outcome
        -mtb_glucose,
        # These aren't really "metabolic" variables.
        -mtb_diastolic_blood_pressure,
        -mtb_systolic_blood_pressure
    ) %>% 
    mutate(leg_height_ratio = leg_height_ratio * 100)

project_data_nc <- project_data %>% 
    select(-age_of_t2dm_diagnosis) %>% 
    mutate(t2dm_status = if_else(is.na(t2dm_status), FALSE, t2dm_status))
    # I want to use .regressed_on = c("age", "sex", "body_mass_index")),
    # but there is a problem with one of the variables having "NA/NaN/Inf" error,
    # and I can't resolve it right now. Will do later point.
    mutate(t2dm_status = if_else(is.na(t2dm_status), FALSE, t2dm_status)) %>% 
    na.omit() %>% 
    nc_standardize(.vars = vars(starts_with("mtb_")))
```

```{r make-network}
# metabolic_network <- analyze_nc_network(project_data_nc)
metabolic_data_only <- project_data_nc %>% 
    mutate(sex_number = as.numeric(as.factor(sex))) %>%
    nc_standardize(.vars = vars(starts_with("mtb_")),
                   # TODO: Compare with BMI
                   .regressed_on = c("age", "sex_number", "waist_circumference")) %>% 
    select(starts_with("mtb_"))

metabolic_network <- metabolic_data_only %>% 
    nc_create_network()
# usethis::use_data(metabolic_network, overwrite = TRUE)

network_plot <- metabolic_data_only %>% 
    na.omit() %>% 
    nc_plot_network(metabolic_network,
                    .node_rename_fun = function(x) x %>% 
                        str_remove("mtb_") %>% 
                        str_replace_all("_", " ") %>% 
                        str_to_title())

network_plot
ggsave(here::here("doc/images/network-plot.svg"), network_plot)
```

```{r}
project_data_nc_std <- project_data_nc %>% 
    nc_standardize(.vars = vars(starts_with("mtb_"))) %>% 
    sample_frac(0.15)
```

```{r outcome-model-estimates}
# model_outcome_estimates <- analyze_nc_outcome(project_data_nc, metabolic_network)
# Might have to send this off as a job... takes a long time to run.
model_outcome_estimates <- project_data_nc_std %>%
    nc_outcome_estimates(
        metabolic_network,
        .outcome = "hba1c",
        .adjustment_vars = c("age", "sex", "waist_circumference"),
        .model_function = lm
    )

# usethis::use_data(model_outcome_estimates, overwrite = TRUE)
model_outcome_estimates %>% 
    mutate(term = str_replace(term, "sexMale", "sex")) %>% 
    nc_classify_effects()
```

```{r plot-outcome-estimates}
model_nodes <-
    data_frame(name = c(
        unique(tidy_model_outcome$outcome),
        tidy_model_outcome$index_node
    ))
model_edges <- tidy_model_outcome %>% 
    mutate(to = as.numeric(as.factor(index_node)) + 1,
           from = 1) %>% 
    select(from, to, estimate, p.value)

tbl_graph(nodes = model_nodes,
          edges = model_edges) %>% 
    ggraph("tree") +
    geom_edge_link2(
        aes(colour = estimate, width = -log10(p.value))
        # arrow = grid::arrow(ends = "first", length = unit(0.2, "cm"), type = "closed")
    ) +
    scale_edge_colour_gradient2(mid = "gray80") +
    scale_edge_width(range = c(0.75, 2)) +
    coord_cartesian(xlim = c(-10.1, 10.1)) +
    geom_node_point() +
    geom_node_label(aes(label = name))
```

```{r exposure-model-estimates}
# model_exposure_estimates <- analyze_nc_exposure(project_data_nc, metabolic_network)
model_exposure_estimates <- project_data_nc_std %>%
    nc_exposure_estimates(
        metabolic_network,
        .exposure = "leg_height_ratio",
        .adjustment_vars = c("age", "sex", "waist_circumference"),
        .model_function = lm
    )

# usethis::use_data(model_exposure_estimates, overwrite = TRUE)

model_exposure_estimates %>% 
    mutate(term = str_replace(term, "sexMale", "sex")) %>% 
    nc_classify_effects()

model_exposure_estimates_hgt <- project_data_nc_std %>%
    nc_exposure_estimates(
        metabolic_network,
        .exposure = "standing_height",
        .adjustment_vars = c("age", "sex", "waist_circumference"),
        .model_function = lm
    )

# usethis::use_data(model_exposure_estimates_hgt, overwrite = TRUE)

model_exposure_estimates_hgt %>% 
    mutate(term = str_replace(term, "sexMale", "sex")) %>% 
    nc_classify_effects()

model_exposure_estimates_ll <- project_data_nc_std %>%
    nc_exposure_estimates(
        metabolic_network,
        .exposure = "leg_length",
        .adjustment_vars = c("age", "sex", "waist_circumference"),
        .model_function = lm
    )

# usethis::use_data(model_exposure_estimates_ll, overwrite = TRUE)

model_exposure_estimates_ll %>% 
    mutate(term = str_replace(term, "sexMale", "sex")) %>% 
    nc_classify_effects()
```


```{r plot-exposure-estimates}
model_nodes <-
    data_frame(name = c(
        unique(tidy_model_exposure$exposure),
        tidy_model_exposure$index_node
    ))
model_edges <- tidy_model_exposure %>% 
    mutate(to = as.numeric(as.factor(index_node)) + 1,
           from = 1) %>% 
    select(from, to, estimate, p.value)

tbl_graph(nodes = model_nodes,
          edges = model_edges) %>% 
    ggraph("tree") +
    geom_edge_link2(
        aes(colour = estimate, width = -log10(p.value))
        # arrow = grid::arrow(ends = "first", length = unit(0.2, "cm"), type = "closed")
    ) +
    scale_edge_colour_gradient2(mid = "gray80") +
    scale_edge_width(range = c(0.75, 2)) +
    coord_cartesian(xlim = c(-10.1, 10.1)) +
    geom_node_point() +
    geom_node_label(aes(label = name))
```

```{r}
outcome_results <- model_outcome_estimates %>% 
    mutate(term = str_replace(term, "sexMale", "sex")) %>% 
    nc_classify_effects() %>% 
    mutate(
        direction = case_when(estimate > 0 ~ "(+)",
                              estimate < 0 ~ "(-)",
                              TRUE ~ ""),
        effect = as.character(glue::glue("{direct_effect} {direction}"))
    ) %>%
    select(outcome, index_node, effect) %>% 
    arrange(desc(effect), index_node)
View(outcome_results)
usethis::use_data(outcome_results, overwrite = TRUE)

exposure_results <- bind_rows(
    model_exposure_estimates %>%
        mutate(term = str_replace(term, "sexMale", "sex")) %>%
        nc_classify_effects(),
    model_exposure_estimates_hgt %>%
        mutate(term = str_replace(term, "sexMale", "sex")) %>%
        nc_classify_effects(),
    model_exposure_estimates_ll %>%
        mutate(term = str_replace(term, "sexMale", "sex")) %>%
        nc_classify_effects()
    ) %>%
    mutate(
        direction = case_when(estimate > 0 ~ "(+)",
                              estimate < 0 ~ "(-)",
                              TRUE ~ ""),
        effect = as.character(glue::glue("{direct_effect} {direction}"))
    ) %>%
    select(exposure, index_node, effect) %>%
    arrange(exposure, desc(effect), index_node) %>%
    pivot_wider(names_from = exposure, values_from = effect)
View(exposure_results)
usethis::use_data(exposure_results, overwrite = TRUE)
```


# Title page

Title:

<!-- First, middle initial, last, highest academic degree -->
Authors:

<!-- During time of study. -->
Affiliation:

Corresponding author:

- Name:
- Current address:
- Phone number:
- Fax number:
- Email:

# Abstract

Objective:

Research Design and Methods:

Results:

Conclusions:

# Introduction 

# Research Design and Methods

# Results

# Conclusions

# Acknowledgements

# References

# Tables

# Figures

# Supplemental Material
