
# Initial importing of the UK Biobank dataset -----------------------------

# Run this to get a variable list to use in `col_types` argument of vroom.
initial_import_for_var_list_specs <- function() {
    # TODO: Check that raw_data_filename object/file exists, otherwise use sim data
    ukb_data <- vroom::vroom(raw_data_filename,
                             # Obtained by using `vroom::spec()` on a smaller
                             # subset of the data to read faster.
                             n_max = 25000)

    specs <- capture.output(vroom::spec(ukb_data))
    clipr::write_clip(specs)
    cli::cli_alert_info("Specs are copied to the clipboard, you can paste them into the vroom function.")
    return(invisible(specs))
}

import_data_with_specific_columns <- function() {
    # TODO: Check that raw_data_filename object/file exists, otherwise use sim data
    ukbiobank_df <- vroom(
        raw_data_filename,
        # Obtained by using `initial_import_for_var_list_specs()` and types are edited.
        col_types = cols_only(
            eid = col_double(),
            sex_f31_0_0 = col_character(),
            year_of_birth_f34_0_0 = col_double(),
            hand_grip_strength_left_f46_0_0 = col_double(),
            hand_grip_strength_left_f46_1_0 = col_double(),
            hand_grip_strength_left_f46_2_0 = col_double(),
            hand_grip_strength_left_f46_3_0 = col_double(),
            hand_grip_strength_right_f47_0_0 = col_double(),
            hand_grip_strength_right_f47_1_0 = col_double(),
            hand_grip_strength_right_f47_2_0 = col_double(),
            hand_grip_strength_right_f47_3_0 = col_double(),
            waist_circumference_f48_0_0 = col_double(),
            waist_circumference_f48_1_0 = col_double(),
            waist_circumference_f48_2_0 = col_double(),
            waist_circumference_f48_3_0 = col_double(),
            hip_circumference_f49_0_0 = col_double(),
            hip_circumference_f49_1_0 = col_double(),
            hip_circumference_f49_2_0 = col_double(),
            hip_circumference_f49_3_0 = col_double(),
            standing_height_f50_0_0 = col_double(),
            standing_height_f50_1_0 = col_double(),
            standing_height_f50_2_0 = col_double(),
            standing_height_f50_3_0 = col_double(),
            date_of_attending_assessment_centre_f53_0_0 = col_date(format = ""),
            date_of_attending_assessment_centre_f53_1_0 = col_date(format = ""),
            date_of_attending_assessment_centre_f53_2_0 = col_date(format = ""),
            date_of_attending_assessment_centre_f53_3_0 = col_date(format = ""),
            uk_biobank_assessment_centre_f54_0_0 = col_double(),
            uk_biobank_assessment_centre_f54_1_0 = col_double(),
            uk_biobank_assessment_centre_f54_2_0 = col_double(),
            uk_biobank_assessment_centre_f54_3_0 = col_double(),
            pulse_rate_automated_reading_f102_0_0 = col_double(),
            pulse_rate_automated_reading_f102_0_1 = col_double(),
            pulse_rate_automated_reading_f102_1_0 = col_double(),
            pulse_rate_automated_reading_f102_1_1 = col_double(),
            pulse_rate_automated_reading_f102_2_0 = col_double(),
            pulse_rate_automated_reading_f102_2_1 = col_double(),
            pulse_rate_automated_reading_f102_3_0 = col_double(),
            pulse_rate_automated_reading_f102_3_1 = col_double(),
            birth_weight_known_f120_0_0 = col_character(),
            birth_weight_known_f120_1_0 = col_character(),
            birth_weight_known_f120_2_0 = col_character(),
            reason_lost_to_followup_f190_0_0 = col_character(),
            date_lost_to_followup_f191_0_0 = col_date(format = ""),
            country_of_birth_ukelsewhere_f1647_0_0 = col_character(),
            country_of_birth_ukelsewhere_f1647_1_0 = col_character(),
            country_of_birth_ukelsewhere_f1647_2_0 = col_character(),
            breastfed_as_a_baby_f1677_0_0 = col_character(),
            breastfed_as_a_baby_f1677_1_0 = col_character(),
            breastfed_as_a_baby_f1677_2_0 = col_character(),
            maternal_smoking_around_birth_f1787_0_0 = col_character(),
            maternal_smoking_around_birth_f1787_1_0 = col_character(),
            maternal_smoking_around_birth_f1787_2_0 = col_character(),
            diastolic_blood_pressure_automated_reading_f4079_0_0 = col_double(),
            diastolic_blood_pressure_automated_reading_f4079_0_1 = col_double(),
            diastolic_blood_pressure_automated_reading_f4079_1_0 = col_double(),
            diastolic_blood_pressure_automated_reading_f4079_1_1 = col_double(),
            diastolic_blood_pressure_automated_reading_f4079_2_0 = col_double(),
            diastolic_blood_pressure_automated_reading_f4079_2_1 = col_double(),
            diastolic_blood_pressure_automated_reading_f4079_3_0 = col_double(),
            diastolic_blood_pressure_automated_reading_f4079_3_1 = col_double(),
            systolic_blood_pressure_automated_reading_f4080_0_0 = col_double(),
            systolic_blood_pressure_automated_reading_f4080_0_1 = col_double(),
            systolic_blood_pressure_automated_reading_f4080_1_0 = col_double(),
            systolic_blood_pressure_automated_reading_f4080_1_1 = col_double(),
            systolic_blood_pressure_automated_reading_f4080_2_0 = col_double(),
            systolic_blood_pressure_automated_reading_f4080_2_1 = col_double(),
            systolic_blood_pressure_automated_reading_f4080_3_0 = col_double(),
            systolic_blood_pressure_automated_reading_f4080_3_1 = col_double(),
            height_f12144_2_0 = col_double(),
            height_f12144_3_0 = col_double(),
            sitting_height_f20015_0_0 = col_double(),
            sitting_height_f20015_1_0 = col_double(),
            sitting_height_f20015_2_0 = col_double(),
            sitting_height_f20015_3_0 = col_double(),
            birth_weight_f20022_0_0 = col_double(),
            birth_weight_f20022_1_0 = col_double(),
            birth_weight_f20022_2_0 = col_double(),
            country_of_birth_nonuk_origin_f20115_0_0 = col_double(),
            felt_hated_by_family_member_as_a_child_f20487_0_0 = col_character(),
            physically_abused_by_family_as_a_child_f20488_0_0 = col_character(),
            felt_loved_as_a_child_f20489_0_0 = col_character(),
            sexually_molested_as_a_child_f20490_0_0 = col_character(),
            someone_to_take_to_doctor_when_needed_as_a_child_f20491_0_0 = col_character(),
            ethnic_background_f21000_0_0 = col_character(),
            ethnic_background_f21000_1_0 = col_character(),
            ethnic_background_f21000_2_0 = col_character(),
            body_mass_index_bmi_f21001_0_0 = col_double(),
            body_mass_index_bmi_f21001_1_0 = col_double(),
            body_mass_index_bmi_f21001_2_0 = col_double(),
            body_mass_index_bmi_f21001_3_0 = col_double(),
            weight_f21002_0_0 = col_double(),
            weight_f21002_1_0 = col_double(),
            weight_f21002_2_0 = col_double(),
            weight_f21002_3_0 = col_double(),
            age_when_attended_assessment_centre_f21003_0_0 = col_double(),
            age_when_attended_assessment_centre_f21003_1_0 = col_double(),
            age_when_attended_assessment_centre_f21003_2_0 = col_double(),
            age_when_attended_assessment_centre_f21003_3_0 = col_double(),
            summed_met_minutes_per_week_for_all_activity_f22040_0_0 = col_double(),
            year_of_birth_f22200_0_0 = col_double(),
            liver_iron_fe_f22400_0_0 = col_double(),
            liver_inflammation_factor_lif_f22401_0_0 = col_double(),
            proton_density_fat_fraction_pdff_f22402_2_0 = col_double(),
            visceral_adipose_tissue_volume_vat_f22407_2_0 = col_double(),
            abdominal_subcutaneous_adipose_tissue_volume_asat_f22408_2_0 = col_double(),
            total_thigh_muscle_volume_f22409_2_0 = col_double(),
            total_trunk_fat_volume_f22410_2_0 = col_double(),
            weight_f23098_0_0 = col_double(),
            weight_f23098_1_0 = col_double(),
            weight_f23098_2_0 = col_double(),
            weight_f23098_3_0 = col_double(),
            body_fat_percentage_f23099_0_0 = col_double(),
            body_fat_percentage_f23099_1_0 = col_double(),
            body_fat_percentage_f23099_2_0 = col_double(),
            body_fat_percentage_f23099_3_0 = col_double(),
            whole_body_fat_mass_f23100_0_0 = col_double(),
            whole_body_fat_mass_f23100_1_0 = col_double(),
            whole_body_fat_mass_f23100_2_0 = col_double(),
            whole_body_fat_mass_f23100_3_0 = col_double(),
            whole_body_fatfree_mass_f23101_0_0 = col_double(),
            whole_body_fatfree_mass_f23101_1_0 = col_double(),
            whole_body_fatfree_mass_f23101_2_0 = col_double(),
            whole_body_fatfree_mass_f23101_3_0 = col_double(),
            whole_body_water_mass_f23102_0_0 = col_double(),
            whole_body_water_mass_f23102_1_0 = col_double(),
            whole_body_water_mass_f23102_2_0 = col_double(),
            whole_body_water_mass_f23102_3_0 = col_double(),
            body_mass_index_bmi_f23104_0_0 = col_double(),
            body_mass_index_bmi_f23104_1_0 = col_double(),
            body_mass_index_bmi_f23104_2_0 = col_double(),
            body_mass_index_bmi_f23104_3_0 = col_double(),
            basal_metabolic_rate_f23105_0_0 = col_double(),
            basal_metabolic_rate_f23105_1_0 = col_double(),
            basal_metabolic_rate_f23105_2_0 = col_double(),
            basal_metabolic_rate_f23105_3_0 = col_double(),
            impedance_of_whole_body_f23106_0_0 = col_double(),
            impedance_of_whole_body_f23106_1_0 = col_double(),
            impedance_of_whole_body_f23106_2_0 = col_double(),
            impedance_of_whole_body_f23106_3_0 = col_double(),
            impedance_of_leg_right_f23107_0_0 = col_double(),
            impedance_of_leg_right_f23107_1_0 = col_double(),
            impedance_of_leg_right_f23107_2_0 = col_double(),
            impedance_of_leg_right_f23107_3_0 = col_double(),
            impedance_of_leg_left_f23108_0_0 = col_double(),
            impedance_of_leg_left_f23108_1_0 = col_double(),
            impedance_of_leg_left_f23108_2_0 = col_double(),
            impedance_of_leg_left_f23108_3_0 = col_double(),
            impedance_of_arm_right_f23109_0_0 = col_double(),
            impedance_of_arm_right_f23109_1_0 = col_double(),
            impedance_of_arm_right_f23109_2_0 = col_double(),
            impedance_of_arm_right_f23109_3_0 = col_double(),
            impedance_of_arm_left_f23110_0_0 = col_double(),
            impedance_of_arm_left_f23110_1_0 = col_double(),
            impedance_of_arm_left_f23110_2_0 = col_double(),
            impedance_of_arm_left_f23110_3_0 = col_double(),
            leg_fat_percentage_right_f23111_0_0 = col_double(),
            leg_fat_percentage_right_f23111_1_0 = col_double(),
            leg_fat_percentage_right_f23111_2_0 = col_double(),
            leg_fat_percentage_right_f23111_3_0 = col_double(),
            leg_fat_mass_right_f23112_0_0 = col_double(),
            leg_fat_mass_right_f23112_1_0 = col_double(),
            leg_fat_mass_right_f23112_2_0 = col_double(),
            leg_fat_mass_right_f23112_3_0 = col_double(),
            leg_fatfree_mass_right_f23113_0_0 = col_double(),
            leg_fatfree_mass_right_f23113_1_0 = col_double(),
            leg_fatfree_mass_right_f23113_2_0 = col_double(),
            leg_fatfree_mass_right_f23113_3_0 = col_double(),
            leg_predicted_mass_right_f23114_0_0 = col_double(),
            leg_predicted_mass_right_f23114_1_0 = col_double(),
            leg_predicted_mass_right_f23114_2_0 = col_double(),
            leg_predicted_mass_right_f23114_3_0 = col_double(),
            leg_fat_percentage_left_f23115_0_0 = col_double(),
            leg_fat_percentage_left_f23115_1_0 = col_double(),
            leg_fat_percentage_left_f23115_2_0 = col_double(),
            leg_fat_percentage_left_f23115_3_0 = col_double(),
            leg_fat_mass_left_f23116_0_0 = col_double(),
            leg_fat_mass_left_f23116_1_0 = col_double(),
            leg_fat_mass_left_f23116_2_0 = col_double(),
            leg_fat_mass_left_f23116_3_0 = col_double(),
            leg_fatfree_mass_left_f23117_0_0 = col_double(),
            leg_fatfree_mass_left_f23117_1_0 = col_double(),
            leg_fatfree_mass_left_f23117_2_0 = col_double(),
            leg_fatfree_mass_left_f23117_3_0 = col_double(),
            leg_predicted_mass_left_f23118_0_0 = col_double(),
            leg_predicted_mass_left_f23118_1_0 = col_double(),
            leg_predicted_mass_left_f23118_2_0 = col_double(),
            leg_predicted_mass_left_f23118_3_0 = col_double(),
            arm_fat_percentage_right_f23119_0_0 = col_double(),
            arm_fat_percentage_right_f23119_1_0 = col_double(),
            arm_fat_percentage_right_f23119_2_0 = col_double(),
            arm_fat_percentage_right_f23119_3_0 = col_double(),
            arm_fat_mass_right_f23120_0_0 = col_double(),
            arm_fat_mass_right_f23120_1_0 = col_double(),
            arm_fat_mass_right_f23120_2_0 = col_double(),
            arm_fat_mass_right_f23120_3_0 = col_double(),
            arm_fatfree_mass_right_f23121_0_0 = col_double(),
            arm_fatfree_mass_right_f23121_1_0 = col_double(),
            arm_fatfree_mass_right_f23121_2_0 = col_double(),
            arm_fatfree_mass_right_f23121_3_0 = col_double(),
            arm_predicted_mass_right_f23122_0_0 = col_double(),
            arm_predicted_mass_right_f23122_1_0 = col_double(),
            arm_predicted_mass_right_f23122_2_0 = col_double(),
            arm_predicted_mass_right_f23122_3_0 = col_double(),
            arm_fat_percentage_left_f23123_0_0 = col_double(),
            arm_fat_percentage_left_f23123_1_0 = col_double(),
            arm_fat_percentage_left_f23123_2_0 = col_double(),
            arm_fat_percentage_left_f23123_3_0 = col_double(),
            arm_fat_mass_left_f23124_0_0 = col_double(),
            arm_fat_mass_left_f23124_1_0 = col_double(),
            arm_fat_mass_left_f23124_2_0 = col_double(),
            arm_fat_mass_left_f23124_3_0 = col_double(),
            arm_fatfree_mass_left_f23125_0_0 = col_double(),
            arm_fatfree_mass_left_f23125_1_0 = col_double(),
            arm_fatfree_mass_left_f23125_2_0 = col_double(),
            arm_fatfree_mass_left_f23125_3_0 = col_double(),
            arm_predicted_mass_left_f23126_0_0 = col_double(),
            arm_predicted_mass_left_f23126_1_0 = col_double(),
            arm_predicted_mass_left_f23126_2_0 = col_double(),
            arm_predicted_mass_left_f23126_3_0 = col_double(),
            trunk_fat_percentage_f23127_0_0 = col_double(),
            trunk_fat_percentage_f23127_1_0 = col_double(),
            trunk_fat_percentage_f23127_2_0 = col_double(),
            trunk_fat_percentage_f23127_3_0 = col_double(),
            trunk_fat_mass_f23128_0_0 = col_double(),
            trunk_fat_mass_f23128_1_0 = col_double(),
            trunk_fat_mass_f23128_2_0 = col_double(),
            trunk_fat_mass_f23128_3_0 = col_double(),
            trunk_fatfree_mass_f23129_0_0 = col_double(),
            trunk_fatfree_mass_f23129_1_0 = col_double(),
            trunk_fatfree_mass_f23129_2_0 = col_double(),
            trunk_fatfree_mass_f23129_3_0 = col_double(),
            trunk_predicted_mass_f23130_0_0 = col_double(),
            trunk_predicted_mass_f23130_1_0 = col_double(),
            trunk_predicted_mass_f23130_2_0 = col_double(),
            trunk_predicted_mass_f23130_3_0 = col_double(),
            android_bone_mass_f23244_2_0 = col_double(),
            android_fat_mass_f23245_2_0 = col_double(),
            android_lean_mass_f23246_2_0 = col_double(),
            android_tissue_fat_percentage_f23247_2_0 = col_double(),
            android_total_mass_f23248_2_0 = col_double(),
            arm_fat_mass_left_f23249_2_0 = col_double(),
            arm_lean_mass_left_f23250_2_0 = col_double(),
            arm_tissue_fat_percentage_left_f23251_2_0 = col_double(),
            arm_total_mass_left_f23252_2_0 = col_double(),
            arm_fat_mass_right_f23253_2_0 = col_double(),
            arm_lean_mass_right_f23254_2_0 = col_double(),
            arm_tissue_fat_percentage_right_f23255_2_0 = col_double(),
            arm_total_mass_right_f23256_2_0 = col_double(),
            arms_fat_mass_f23257_2_0 = col_double(),
            arms_lean_mass_f23258_2_0 = col_double(),
            arms_tissue_fat_percentage_f23259_2_0 = col_double(),
            arms_total_mass_f23260_2_0 = col_double(),
            gynoid_bone_mass_f23261_2_0 = col_double(),
            gynoid_fat_mass_f23262_2_0 = col_double(),
            gynoid_lean_mass_f23263_2_0 = col_double(),
            gynoid_tissue_fat_percentage_f23264_2_0 = col_double(),
            gynoid_total_mass_f23265_2_0 = col_double(),
            leg_fat_mass_left_f23266_2_0 = col_double(),
            leg_lean_mass_left_f23267_2_0 = col_double(),
            leg_tissue_fat_percentage_left_f23268_2_0 = col_double(),
            leg_total_mass_left_f23269_2_0 = col_double(),
            leg_fat_mass_right_f23270_2_0 = col_double(),
            leg_lean_mass_right_f23271_2_0 = col_double(),
            leg_tissue_fat_percentage_right_f23272_2_0 = col_double(),
            leg_total_mass_right_f23273_2_0 = col_double(),
            legs_fat_mass_f23274_2_0 = col_double(),
            legs_lean_mass_f23275_2_0 = col_double(),
            legs_tissue_fat_percentage_f23276_2_0 = col_double(),
            legs_total_mass_f23277_2_0 = col_double(),
            total_fat_mass_f23278_2_0 = col_double(),
            total_fatfree_mass_f23279_2_0 = col_double(),
            total_lean_mass_f23280_2_0 = col_double(),
            total_tissue_fat_percentage_f23281_2_0 = col_double(),
            total_tissue_mass_f23282_2_0 = col_double(),
            total_mass_f23283_2_0 = col_double(),
            trunk_fat_mass_f23284_2_0 = col_double(),
            trunk_lean_mass_f23285_2_0 = col_double(),
            trunk_tissue_fat_percentage_f23286_2_0 = col_double(),
            trunk_total_mass_f23287_2_0 = col_double(),
            vat_visceral_adipose_tissue_mass_f23288_2_0 = col_double(),
            vat_visceral_adipose_tissue_volume_f23289_2_0 = col_double(),
            index_of_multiple_deprivation_england_f26410_0_0 = col_double(),
            index_of_multiple_deprivation_wales_f26426_0_0 = col_double(),
            index_of_multiple_deprivation_scotland_f26427_0_0 = col_double(),
            microalbumin_in_urine_f30500_0_0 = col_double(),
            microalbumin_in_urine_f30500_1_0 = col_double(),
            creatinine_enzymatic_in_urine_f30510_0_0 = col_double(),
            creatinine_enzymatic_in_urine_f30510_1_0 = col_double(),
            albumin_f30600_0_0 = col_double(),
            albumin_f30600_1_0 = col_double(),
            alanine_aminotransferase_f30620_0_0 = col_double(),
            alanine_aminotransferase_f30620_1_0 = col_double(),
            apolipoprotein_a_f30630_0_0 = col_double(),
            apolipoprotein_a_f30630_1_0 = col_double(),
            apolipoprotein_b_f30640_0_0 = col_double(),
            apolipoprotein_b_f30640_1_0 = col_double(),
            aspartate_aminotransferase_f30650_0_0 = col_double(),
            aspartate_aminotransferase_f30650_1_0 = col_double(),
            cholesterol_f30690_0_0 = col_double(),
            cholesterol_f30690_1_0 = col_double(),
            creatinine_f30700_0_0 = col_double(),
            creatinine_f30700_1_0 = col_double(),
            creactive_protein_f30710_0_0 = col_double(),
            creactive_protein_f30710_1_0 = col_double(),
            gamma_glutamyltransferase_f30730_0_0 = col_double(),
            gamma_glutamyltransferase_f30730_1_0 = col_double(),
            glucose_f30740_0_0 = col_double(),
            glucose_f30740_1_0 = col_double(),
            glycated_haemoglobin_hba1c_f30750_0_0 = col_double(),
            glycated_haemoglobin_hba1c_f30750_1_0 = col_double(),
            hdl_cholesterol_f30760_0_0 = col_double(),
            hdl_cholesterol_f30760_1_0 = col_double(),
            ldl_direct_f30780_0_0 = col_double(),
            ldl_direct_f30780_1_0 = col_double(),
            lipoprotein_a_f30790_0_0 = col_double(),
            lipoprotein_a_f30790_1_0 = col_double(),
            triglycerides_f30870_0_0 = col_double(),
            triglycerides_f30870_1_0 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_0 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_1 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_2 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_3 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_4 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_5 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_6 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_7 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_8 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_9 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_10 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_11 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_12 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_13 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_14 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_15 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_16 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_17 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_18 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_19 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_20 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_21 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_22 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_23 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_24 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_25 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_26 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_27 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_28 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_29 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_30 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_31 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_32 = col_double(),
            noncancer_illness_code_selfreported_f20002_0_33 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_0 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_1 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_2 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_3 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_4 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_5 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_6 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_7 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_8 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_9 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_10 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_11 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_12 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_13 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_14 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_15 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_16 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_17 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_18 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_19 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_20 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_21 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_22 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_23 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_24 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_25 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_26 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_27 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_28 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_29 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_30 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_31 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_32 = col_double(),
            noncancer_illness_code_selfreported_f20002_1_33 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_0 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_1 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_2 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_3 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_4 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_5 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_6 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_7 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_8 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_9 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_10 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_11 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_12 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_13 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_14 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_15 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_16 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_17 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_18 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_19 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_20 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_21 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_22 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_23 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_24 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_25 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_26 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_27 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_28 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_29 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_30 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_31 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_32 = col_double(),
            noncancer_illness_code_selfreported_f20002_2_33 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_0 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_1 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_2 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_3 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_4 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_5 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_6 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_7 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_8 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_9 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_10 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_11 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_12 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_13 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_14 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_15 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_16 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_17 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_18 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_19 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_20 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_21 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_22 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_23 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_24 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_25 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_26 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_27 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_28 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_29 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_30 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_31 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_32 = col_double(),
            noncancer_illness_code_selfreported_f20002_3_33 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_0 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_1 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_2 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_3 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_4 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_5 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_6 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_7 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_8 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_9 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_10 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_11 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_12 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_13 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_14 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_15 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_16 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_17 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_18 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_19 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_20 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_21 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_22 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_23 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_24 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_25 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_26 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_27 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_28 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_29 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_30 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_31 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_32 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_0_33 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_0 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_1 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_2 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_3 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_4 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_5 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_6 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_7 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_8 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_9 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_10 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_11 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_12 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_13 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_14 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_15 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_16 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_17 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_18 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_19 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_20 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_21 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_22 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_23 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_24 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_25 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_26 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_27 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_28 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_29 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_30 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_31 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_32 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_1_33 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_0 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_1 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_2 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_3 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_4 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_5 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_6 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_7 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_8 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_9 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_10 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_11 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_12 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_13 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_14 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_15 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_16 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_17 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_18 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_19 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_20 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_21 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_22 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_23 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_24 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_25 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_26 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_27 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_28 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_29 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_30 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_31 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_32 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_2_33 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_0 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_1 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_2 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_3 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_4 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_5 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_6 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_7 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_8 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_9 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_10 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_11 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_12 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_13 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_14 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_15 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_16 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_17 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_18 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_19 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_20 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_21 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_22 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_23 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_24 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_25 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_26 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_27 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_28 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_29 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_30 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_31 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_32 = col_double(),
            interpolated_age_of_participant_when_noncancer_illness_first_diagnosed_f20009_3_33 = col_double(),
        )
    )

    if (interactive()) beepr::beep(4)
    return(ukbiobank_df)
}

drop_empty_or_only_false_cols <- function(x) {
    if (is.character(x) | inherits(x, "Date")) {
        TRUE
    } else {
        sum(x, na.rm = TRUE) != 0
    }
}

calc_leg_measures <- function(.tbl) {
    .tbl %>%
        mutate(
            leg_length_0_0 = standing_height_f50_0_0 - sitting_height_f20015_0_0,
            leg_height_ratio_0_0 = leg_length_0_0 / standing_height_f50_0_0
        ) %>%
        # Drop too large or too small values
        # TODO: Confirm this in EDA Rmd file or something.
        dplyr::filter(leg_length_0_0 < 120, leg_length_0_0 > 60)
}

calc_t2dm_status <- function(.tbl) {
    # Convert to long form to extract age of diagnosis and t2dm illness.
    longer_data <- .tbl %>%
        select(eid,
               matches("^(noncancer_illness|interpolated_age).*_0_[0-9]+$")) %>%
        tidyr::pivot_longer(
            cols = -eid,
            names_to = c("Variables", "Items"),
            names_pattern = "(^.*)_f[0-9]+_([0-9]_[0-9]+$)",
            values_to = "Values"
        ) %>%
        dplyr::filter(!is.na(Values))

    # Convert to wide form so age and illness match up.
    wider_data <- longer_data %>%
        tidyr::pivot_wider(names_from = Variables, values_from = Values) %>%
        rename(illness_code = noncancer_illness_code_selfreported,
               age_of_t2dm_diagnosis_0_0 = interpolated_age_of_participant_when_noncancer_illness_first_diagnosed) %>%
        # Convert illness variables to either with or without type 2 diabetes
        # (code for t2dm = 1223)
        mutate(t2dm_status_0_0 = if_else(illness_code == 1223, TRUE, FALSE)) %>%
        dplyr::filter(t2dm_status_0_0) %>%
        # To confirm no duplicate eid
        assertr::assert(assertr::is_uniq, eid) %>%
        select(eid, t2dm_status_0_0, age_of_t2dm_diagnosis_0_0)

    left_join(.tbl, wider_data, by = "eid")
}

#' Wrangle and prepare the loaded UK Biobank dataset.
#'
#' @param .save Optional. Save wrangled and trimmed down dataset to server.
#'
#' @return A tibble data frame object.
#'
#' @examples
#'
#' ukb_prep <- wrangle_ukb_data()
#' ukb_prep %>%
#' count(t2dm_status_0_0)
#' ukb_prep %>%
#' View()
#' skimr::skim(ukb_prep) %>%
#' View()
#' wrangle_ukb_data(.save = TRUE)
wrangle_ukb_data <- function(.save = FALSE) {
    # The below code gets the data, but better to run a local job (in RStudio)
    # using the `R/jobs/loading-raw.R` file to load the dataset into the global
    # environment, *before* running this function.
    # Use run_job_loading_raw() function to start this job.
    # ukb_data_raw <- import_data_with_specific_columns()

    # Wrangle loaded ukb_data_raw.
    ukb_data_smaller <- ukb_data_raw %>%
        # Filter out type 1 diabetes (code for t1dm = 1222)
        filter_at(vars(matches("^noncancer_illness_")),
                  all_vars(. != 1222 |
                               is.na(.))) %>%
        # Drop missing sitting heights
        dplyr::filter(!is.na(sitting_height_f20015_0_0)) %>%
        # Drop too big or too small values
        dplyr::filter(
            standing_height_f50_0_0 > 148,
            hip_circumference_f49_0_0 > 20,
            body_mass_index_bmi_f21001_0_0 > 18.5
        ) %>%
        calc_leg_measures() %>%
        calc_t2dm_status()

    ukb_data_smallest <- ukb_data_smaller %>%
        select_if(drop_empty_or_only_false_cols) %>%
        # Keep only first visit variables
        select(
            eid,
            ends_with("0_0"),
            matches("^(diastolic|systolic)_.*0_[0-1]$"),
            -matches("noncancer|interpolated")
        )

    if (.save) {
        vroom_write(ukb_data_smallest, project_data_filename, delim = ",")
    }
    ukb_data_smallest
}

# Prepare code for use in NetCoupler --------------------------------------

prepare_data_for_netcoupler_analysis <- function(file_path) {
    project_data <- load_data(file_path) %>%
        dplyr::rename(hba1c = mtb_glycated_haemoglobin_hba1c) %>%
        dplyr::select(
            # More than 25% missing for these variables.
            -mtb_microalbumin_in_urine,
            -mtb_lipoprotein_a,
            # Glucose should probably not be in models with HbA1c as outcom
            -mtb_glucose,
            # These aren't really "metabolic" variables
            -mtb_diastolic_blood_pressure,
            -mtb_systolic_blood_pressure,
            # Since these associate with muscle mass (which is associated with height)
            # Actually, keep them in for verification against height
            -mtb_creatinine,
            -mtb_creatinine_enzymatic_in_urine
        ) %>%
        dplyr::mutate(leg_height_ratio = leg_height_ratio * 100)

    project_data_nc <- project_data %>%
        dplyr::select(-age_of_t2dm_diagnosis) %>%
        dplyr::mutate(t2dm_status = dplyr::if_else(is.na(t2dm_status), FALSE, t2dm_status))

    rsample::initial_split(project_data_nc)
}

create_cv_splits <- function(.training_data) {
    .training_data %>%
        rsample::mc_cv(prop = 0.10, times = 100)
}

